import { USER_FIELDS } from '@constants';

const USER_FIELDS_PLACEHOLDER = {
  [USER_FIELDS.NAME]: 'Enter Name',
  [USER_FIELDS.EMAIL]: 'Enter Email',
  [USER_FIELDS.PHONE]: 'Enter Phone',
  [USER_FIELDS.COUNTRY]: 'Select Country',
};

const USER_FIELDS_VALIDATION = [USER_FIELDS.NAME, USER_FIELDS.COUNTRY, USER_FIELDS.PHONE, USER_FIELDS.EMAIL];

export { USER_FIELDS_PLACEHOLDER, USER_FIELDS_VALIDATION };